### ISSUE TITLE
SCPToRemote not working

### ISSUE THREAD

**Issue by randohinn** [tmaxeiner/TSSHCommand#2]
Hi. I'm trying to use this unit to scp a file to a remote host.

Running ssh commands on the remote host with the ssh method works. SCP does not - the file does not appear on the remote. However, if I print the SCP to remote param string, and paste that into the commandline after scp.exe, everything works fine. Both ssh.exe and scp.exe have been copied to the application folder. What should I do to debug this more and make it function?

**Comment by tmaxeiner** [comment]
If the ssh command demo works, then you should have a correct keyfile and entry in knownhost. Eventually you have unicode chars or spaces in your source and destination names? Could be that the shellexecute command goes wrong with unicode or spaces. Especially spaces I think are bad, even if command line test will work. If so, try to surround your originals strings with " chars. You can test this on command line too.

**Comment by randohinn** [comment]
Fixed with the help of SW_SHOWNORMAL and a screen recording of the cmd window popping up - FSSHClient was not being set to scp.exe so it tried to perform scp using ssh.exe.... which is not how that works at all 😆
